name: Terraform & App Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
      RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
      COGNITIVE_ACCOUNT_NAME: ${{ vars.COGNITIVE_ACCOUNT_NAME }}
      COGNITIVE_DEPLOYMENT_NAME: ${{ vars.COGNITIVE_DEPLOYMENT_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ">=1.1.0"

      - name: Terraform Init
        run: terraform init

      - name: Make import_resources.sh executable
        run: chmod +x ./import_resources.sh

      - name: Import existing resources
        run: ./import_resources.sh

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  deploy:
    name: "Deploy to Azure Web App"
    runs-on: ubuntu-latest
    needs: terraform
    env:
      WEB_APP_NAME: ${{ vars.WEB_APP_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.WEB_APP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./webapp